#!/usr/intel/bin/tcsh -f

set realpath = `realpath $0`
set scriptdir = `dirname $realpath`

env -i /usr/intel/pkgs/openjdk/11.0.17/bin/java -Djavax.net.ssl.trustStore=/p/psg/da/infra/admin/jenkins/cacert_related/cacerts -jar $scriptdir/jenkins-cli.jar -auth psgcicq_tc:11db7dae53664b5da2b643af7e539b99c2 -s https://cje-fm-owrp-prod03.devtools.intel.com/psg-infra-cicq/ $argv:q
